### ISSUE TITLE
Changing Default colors and styles (variables)

### ISSUE THREAD

**Issue by M-Barari** [avil13/vue-sweetalert2#122]
I'm using Nuxt 2.13 and gonna change the colors and style of sweet alert. actually i did it and it was working , but recently i saw that it's not working anymore!!
i created a scss file: 

``` scss
@import '/variables.scss';
@import '~sweetalert2/src/variables';
@import '~sweetalert2/src/sweetalert2';

$swal2-success: $theme_color_success;
$swal2-error: $theme_color_danger;
$swal2-warning: $theme_color_warning;
$swal2-info: $theme_color_primary;
$swal2-confirm-button-background-color: $theme_color_success;
$swal2-cancel-button-background-color: $theme_color_danger;


.swal2-popup{
    font-family: $font_family_fa;
    direction: rtl;
}
```

and added it to my nuxt.config.js file.

what exactly happend !!? and how can i achieve it again?
