### ISSUE TITLE
Wrong CSS

### ISSUE THREAD

**Issue by matze1708** [avil13/vue-sweetalert2#140]
Hi guys,

i have an problem, i implemented Sweetalert like so:
```
import Vue from 'vue';
import VueSweetalert2 from 'vue-sweetalert2';
import 'sweetalert2/dist/sweetalert2.min.css';

// const options = {
//     confirmButtonColor: '#41b882',
//     cancelButtonColor: '#ff7674',
// };

const Sweet = Vue.use(VueSweetalert2);

export default Sweet;

```

But i have no option to change Text Style. The Text Style is simply Times-New-Roman. 
Is there any possibility to change this?

Thank you.

**Comment by avil13** [comment]
Hello.
Why don't you just try writing the desired style to the element?
```css
.swal2-title {
    font-family: monospace; // Choose a font
}
```
<img width="398" alt="image" src="https://user-images.githubusercontent.com/1606172/147570581-b3f00372-53f6-4e8a-9865-d23edb2600fe.png">

**Comment by matze1708** [comment]
I don't know how to do that, where do I put it?

**Comment by avil13** [comment]
The easiest thing to do.
Create a new styles file.
Fill it in
```css
.swal2-container {
    font-family: monospace; /* here is your font */.
}
```
And include it after ` import 'sweetalert2/dist/sweetalert2.min.css'; `

```css
import 'sweetalert2/dist/sweetalert2.min.css'; 
import 'path/to/my/style.css';
```
